_core:
  default_config_hash: RePADAH4yHzDAKh-gEsDxPFK9hQe32l4p4t8Cqryww8
langcode: en
uuid: 0c28a7d4-fb64-4d82-a1ad-35808fee000e
name: 'Sam''s site!'
mail: admin@example.com
slogan: 'A blogging profile for Tome users'
page:
  403: /403
  404: /404
  front: /home
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
